
@echo off
chcp 65001

set FINAL_FILENAME=Liyuu的首次广播-#56-v3
set ORIGINAL_AUDIO_VIDEO_PATH=#56.mp3
set AAC_AUDIO_PATH=audio_AAC.mp4
set COVER_PATH=广播56回封面16.9.png
set SUBTITLE_PATH=首次广播#56-发布稿v3.ass
set SUBTITLE_VSFM_PATH=
set BASE_VIDEO_GOP_LENGTH=5
set BASE_VIDEO_CRF=16
